# Site settings
title: Šimon Bôrik | Portfolio
description: Šimon Bôrik | Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Šimon Bôrik
user_description: My name is Šimon Bôrik, I am a game developer from Slovakia. I've studied computer graphics and digital image processing in Czech Republic. Currently focused on Unreal Engine C++ and blueprints, I have been employed as a programmer in QORPO s.r.o in Bratislava, Slovakia since November 2021. With some previous experience with Unity C# and VR, I have also developed small game prototypes. You can find more information below and in my CV.
user_title: Game Developer
email: simonborik01@gmail.com
twitter_username: lorem_ipsum
github_username:  SimonBorik
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
